export enum EntityNames {
  User = "user",
  UserOtp = "user_otp",
  UserAddress = "user_address",
  UserBasket = "user_basket",
  Category = "category",
  Supplier = "supplier",
  SupplierOtp = "supplier_otp",
  Menu = "menu",
  MenuItem = "menu_item",
  Feedbacks = "feedback",
  MenuType = "menu-type",
  Discount = "discount",
  Order = "order",
  OrderItem = "order_item",
  Payment = "payment",
}
